name: Install dependencies

on: [workflow_call]

jobs:
  dependencies:
    name: Install dependencies and cache them
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: lts/gallium
      - id: modules-cache
        uses: actions/cache@v2.1.7
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - run: yarn install --frozen-lockfile
        if: steps.modules-cache.outputs.cache-hit != 'true'
