name: Pull request checks

on:
  pull_request:
    branches: [ master, next ]

jobs:
  build:
    name: Run checks for pull request
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/workflows/dependencies
      - run: yarn format:ci
      - run: yarn lint:ci
      - run: yarn typecheck
      - run: yarn test